name: pull request

on: pull_request

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - run: yarn install
      - run: yarn typecheck
      - run: yarn lint
      - run: yarn test
      - run: yarn build
